
var CATEGORIAS = '{"CATEG":[{"CATEGORIA":"ELECTRODOMESTICOS"},{"CATEGORIA":"PEQUEÑOS ELECTRODOMESTICOS"},{"CATEGORIA":"COMPUTACION"},{"CATEGORIA":"ELECTRONICA"},{"CATEGORIA":"ELECTRONICA Y HOGAR"},{"CATEGORIA":"HERRAMIENTAS"},{"CATEGORIA":"JARDIN"},{"CATEGORIA":"SUPERMERCADO"},{"CATEGORIA":"DEPORTES Y FITNESS"},{"CATEGORIA":"MODA"}]}';


